### ISSUE TITLE
禁用下拉刷新报错

### ISSUE THREAD

**Issue by yxxme** [wannaxiao/vue-slim-better-scroll#1]
### 版本
1.2.0

### 代码
`
<Scroll
        ref="scroll"
        :pullDown="false">
</Scroll>
`

源码中
`
this.pullDownInitTop = parseInt(getComputedStyle(this.$refs.pulldown).top) || -50
`
当pullDown禁用的时候getComputedStyle参数非'Element'

**Comment by wannaxiao** [comment]
感谢反馈，1.2.4已修复～
