### ISSUE TITLE
滚动开始前无效， bug?

### ISSUE THREAD

**Issue by Ya-hui** [wannaxiao/vue-slim-better-scroll#10]
源代码
![image](https://user-images.githubusercontent.com/13138164/44631052-4bb45500-a999-11e8-8592-b1ce5ed41432.png)
![image](https://user-images.githubusercontent.com/13138164/44631053-540c9000-a999-11e8-8ce0-fe9cdeed8922.png)
文档
![image](https://user-images.githubusercontent.com/13138164/44631054-62f34280-a999-11e8-8883-fb460ba4c693.png)
我的使用
![image](https://user-images.githubusercontent.com/13138164/44631059-76061280-a999-11e8-9488-71c470054eb9.png)
![image](https://user-images.githubusercontent.com/13138164/44631061-7dc5b700-a999-11e8-9e17-5c8b03b607aa.png)

**Comment by Ya-hui** [comment]
bug?

**Comment by wannaxiao** [comment]
1.4.2已修复，api名字写漏了(ಥ_ಥ)
