### ISSUE TITLE
【问题】vue缓存后，不能滚动

### ISSUE THREAD

**Issue by chengjs** [wannaxiao/vue-slim-better-scroll#15]
1. 进入页面，下拉一定的距离并且加载一些数据
2. 在app.vue中缓存过
3. 在单击进入详情页面
4. 返回在当前滚动页面，你会发现，滚不动。哈哈哈哈

**Comment by wannaxiao** [comment]
v1.5.0 已修复。

示例：https://wannaxiao.github.io/vue-slim-better-scroll/demo/complex/dist/
示例源码：https://github.com/wannaxiao/vue-slim-better-scroll/tree/master/demo/complex
