### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by xintao-taotao** [wannaxiao/vue-slim-better-scroll#19]
上拉的时候，能不能做到松开手之后再刷新，我发现上拉之后，下面会直接刷新，我的项目用了这个插件，现在就是如果一直下拉不放，那么他就一直在刷新数据，这样感觉不太好，希望可以松开手指之后再刷新

**Comment by wannaxiao** [comment]
一个好的用户体验，应该是让用户没有感知的。可以看一下主流app的无限加载，都是在用户还没滚到底部之前，就会提前一定距离触发拉取数据，这样用户滚动的时候加载就是无感知的。所以这样是没有问题的噢

**Comment by wannaxiao** [comment]
下拉刷新就是松手之后才会触发刷新的，可以参考demo

**Comment by xintao-taotao** [comment]
可能我说反了，往上拉的时候，是在下面加载新的数据没错吧，然后我发现就是往上去拉动的时候，下面的数据会直接加载出来，我在上拉的过程中没有松开鼠标，但是还是刷新了数据。我想的就是没松开手之前，上拉只会展示一些文字或者是loading之类的，然后松手才是数据加载

**Comment by wannaxiao** [comment]
关于上拉加载，上面也有解释原因：

> 一个好的用户体验，应该是让用户没有感知的。可以看一下主流app的无限加载，都是在用户还没滚到底部之前，就会提前一定距离触发拉取数据，这样用户滚动的时候加载就是无感知的。所以这样是没有问题的噢
