### ISSUE TITLE
hello 为什么我用initScroll这个方法会报错啊

### ISSUE THREAD

**Issue by yehoan** [wannaxiao/vue-slim-better-scroll#2]
![image](https://user-images.githubusercontent.com/22631753/42205881-3152c67e-7ed8-11e8-9b73-fd2ce6cd424d.png)

**Comment by yehoan** [comment]
这样写有什么问题 我之前在better -scroll 里面使用没问题啊

**Comment by wannaxiao** [comment]
用法有误，查看[文档](https://wannaxiao.github.io/vue-slim-better-scroll/docs/dist/)
