### ISSUE TITLE
为什么在使用时必须给高度才能上拉和下拉?

### ISSUE THREAD

**Issue by 941477276** [wannaxiao/vue-slim-better-scroll#22]
为什么在使用时必须给高度才能上拉和下拉?虽然better-scroll.js设计时必须给父容器设置高度才能生效，但我觉得在编写vue组件高度应该在vue组件内部解决，如果要外部去计算那就很麻烦了

**Comment by wannaxiao** [comment]
height: 100%; 取决与你外部容器的宽高。你也可以直接加一个class覆盖盒子宽高。

**Comment by 941477276** [comment]
**没有给容器设置高度时是无法上拉和下拉的**
![无法上拉和下拉](https://user-images.githubusercontent.com/20528541/60595828-5a9a3e00-9dda-11e9-8898-2da3065fd27e.gif)
**给容器设置高度后可以上拉和下拉**
![可以上拉和下拉](https://user-images.githubusercontent.com/20528541/60595917-7d2c5700-9dda-11e9-8984-3ba7d57c5211.gif)

**Comment by wannaxiao** [comment]
父容器要设置具体的高度。你可以看一下better-scroll的滚动原理：https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/#%E6%BB%9A%E5%8A%A8%E5%8E%9F%E7%90%86

**Comment by wannaxiao** [comment]
height: 100%;就是取外部容器的高度来自适应高度。
你完全可以通过css的手段使得外部容器高度可适应性，从而不用给出具体到px的数值。具体可参考demo。
组件内部是没办法知道，你到底是想要多高的位置来滚动的。
