### ISSUE TITLE
全局引入没有反应

### ISSUE THREAD

**Issue by BackTooHard** [wannaxiao/vue-slim-better-scroll#24]
全局引入组件上拉下拉没反应。
在vue页面中引入组件可以正常使用。
只改变了引入方式，为什么效果会不同。

**Comment by wannaxiao** [comment]
补充一下具体代码

**Comment by BackTooHard** [comment]
![10](https://user-images.githubusercontent.com/29507751/63398630-c7a47a00-c400-11e9-89e6-eb6d75ee3223.png)
![11](https://user-images.githubusercontent.com/29507751/63398687-e99dfc80-c400-11e9-81ac-a23939e20e92.png)
![12](https://user-images.githubusercontent.com/29507751/63398731-0fc39c80-c401-11e9-9317-333f6d96f88a.jpg)

**Comment by wannaxiao** [comment]
全局安装的组件名为 Scroll，你用错名字了
