### ISSUE TITLE
发现问题

### ISSUE THREAD

**Issue by Leader755** [wannaxiao/vue-slim-better-scroll#25]
发现问题：
1.下拉刷新时结束时，有时不会出现刷新成功字样。
2.发现下拉刷新时，有时会触发上拉加载功能，之前以为是我的代码有问题，下载源码后运行也发现了同样的问题。
![scroll-vue](https://user-images.githubusercontent.com/37180494/64075600-c4589a80-ccec-11e9-816a-8873ddb55594.gif)

**Comment by wannaxiao** [comment]
1. 补充better-scroll版本，从node_modules进入，找到better-scroll，查看package.json。
2. 删除node_modules文件夹，使用yarn安装依赖。重复测试。

**Comment by wannaxiao** [comment]
缺少信息
