### ISSUE TITLE
发现一个问题 就是滚动在聊天中不是实时的 滚动到最新的一条 如图

### ISSUE THREAD

**Issue by yehoan** [wannaxiao/vue-slim-better-scroll#3]
![image](https://user-images.githubusercontent.com/22631753/42254942-d7d67ace-7f7b-11e8-8e3b-bb1c77280b7d.png)
![image](https://user-images.githubusercontent.com/22631753/42254990-153e2772-7f7c-11e8-8344-68336b7e6863.png)
![image](https://user-images.githubusercontent.com/22631753/42255021-365d0fd6-7f7c-11e8-86a6-703eb312a4f1.png)
麻烦看下谢谢 真的 就是我发的最新的消息他不会立马呈现而是呈现的是上一条信息  不知道为什么 麻烦看下谢谢

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/42255359-e8633c4a-7f7d-11e8-83b4-af13469584f5.png)
我审查了scroll的高度没问题...

**Comment by yehoan** [comment]
一开始我用自动上拉和下拉的时候
他会自动往上走一行 然后达到刷新高度....

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/42255414-2ed6bcba-7f7e-11e8-8234-5ec33aca5916.png)
元素是这么高 一开始我默认可以上下拉的时候 他直接把我第一次发的信息给他放到另外一页了 ..

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/42255503-a79dd502-7f7e-11e8-8f86-76498fd01315.png)
这个是自动默认可以上拉和下拉  
![image](https://user-images.githubusercontent.com/22631753/42255524-c6c543a2-7f7e-11e8-9d73-c24a7a00e0c6.png)
当我已发送 他自动把第一行的推上去了
![image](https://user-images.githubusercontent.com/22631753/42255583-0933bd18-7f7f-11e8-8258-9f41a84e30ca.png)
但是下面的就会自动推上去 因为他把第一行的就自动推上去了 感觉这个是个问题

**Comment by yehoan** [comment]
因为我做的事聊天 不需要上拉和下拉..

**Comment by yehoan** [comment]
谢谢了

**Comment by yehoan** [comment]
高度没有问题 我感觉是哪里默认的配置有问题真的. 那个scrollToElement 可能有个问题

**Comment by wannaxiao** [comment]
提供一下 demo

**Comment by wannaxiao** [comment]
或使用v1.4.0+的 `scrollToBottom`，查看最新的文档

**Comment by yehoan** [comment]
[#``](url)

**Comment by yehoan** [comment]
好我看一下

**Comment by yehoan** [comment]
文档没看见scrollToBottom..

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/42261220-04339606-7f9a-11e8-8e91-1cd0523c59ef.png)
报错..

**Comment by yehoan** [comment]
没有这个属性..

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/42261856-13194efc-7f9c-11e8-9989-61b387710fc2.png)
maxScrollY 是有值的
