### ISSUE TITLE
为什么我的滚不了.....

### ISSUE THREAD

**Issue by yehoan** [wannaxiao/vue-slim-better-scroll#6]
![image](https://user-images.githubusercontent.com/22631753/43945644-5388c554-9cb5-11e8-9b59-c94c3adff408.png)

**Comment by wannaxiao** [comment]
因为v-if引起了滚动高度的变化。
* 方法一：在 `Scroll` 组件中添加属性 `refreshData`，将引起高度变化的状态放入： `refreshData=[currentShow]`
*方法二：currentShow 状态变化后手动在 $nextTick 回调中调用 `this.refs.scroll.refresh()`

**Comment by wannaxiao** [comment]
详细内容请查看文档： https://wannaxiao.github.io/vue-slim-better-scroll/docs/dist/#props

**Comment by yehoan** [comment]
问题是我都试了 都没有我才问你的 你说的2中方法依然不能滚动...

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/43946289-688ecdc0-9cb7-11e8-8c5c-5fdafacdd76a.png)

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/43946311-7e612d96-9cb7-11e8-8afa-ef2f55b47393.png)

**Comment by wannaxiao** [comment]
@yehoan 看一看父盒子是不是没有固定的高度

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/43946464-ea695a0e-9cb7-11e8-8d81-d3050b6a4913.png)
固定的

**Comment by yehoan** [comment]
我是用flex做的

**Comment by yehoan** [comment]
之前我做那个聊天室都OK的..

**Comment by wannaxiao** [comment]
你这个是遇到了旧浏览器的flex 100% bug了。
* 方法一：父盒子不要用flex。
* 方法二：父盒子加上 相对定位，vue-slim-better-scroll 加上用绝对定位并设置 left right top bottom = 0。

**Comment by wannaxiao** [comment]
@yehoan 那问题就出在 refresh 的时机上了，尝试下自己排查。或者提供下最小的可访问的示例代码

**Comment by yehoan** [comment]
`<template>
  <div class="Mygift_container">
    <MobileHeader>我的获赠</MobileHeader>
    <div class="gift_content">
      <div class="gift_tab">
        <div class="is_cash" :class="{'active':currentShow}" @click="changeTab(1)">已兑现</div>
        <div class="no_cash" :class="{'active':!currentShow}" @click="changeTab(2)">未兑现</div>
      </div>
      

      <div class="isCash_content" v-if="currentShow">
        <noDataTip v-if="isNull"></noDataTip>
        <BScroll
          ref="scroll"
          @pullingDown="loadRefresh"
          @pullingUp="loadMore"
          :refreshData= "[currentShow]"
          v-else
        >
          <div class="discount_ticket"  v-for="(list,num) in isCashArr">
            <div class="left_side">
              <p class="remark_info">{{list.remark}}</p>
              <p class="time_date">至{{timeList[num].TimeList}}过期</p>
              <div class="id_num" style="display: flex"><span style="float:left" class="id">单号:</span><span
                style="width: 70%">{{list.id}}</span></div>
              <div class="middle_line"></div>
            </div>
            <div class="right_side">
              <div class="side_money">¥ {{list.couponValueStr*0.01}}</div>
              <div class="side_num"> ={{list.couponValueStr}}UET</div>
            </div>
          </div>
        </BScroll>
      </div>
      
      <div class="noCash_content" v-else>
        <noDataTip v-if="isNullNext"></noDataTip>
        <b-scroll
          v-else
        >
          <div class="discount_ticket"  v-for="(list,num) in noCacheArr">
            <div class="left_side">
              <p class="remark_info">{{list.remark}}</p>
              <p class="time_date">至{{timeList[num].TimeList}}过期</p>
              <div class="id_num" style="display: flex"><span style="float:left" class="id">单号:</span><span
                style="width: 70%">{{list.id}}</span></div>
              <div class="middle_line_next"></div>
            </div>
            <div class="right_side">
              <div class="side_money">¥ {{list.couponValueStr*0.01}}</div>
              <div class="side_num"> ={{list.couponValueStr}}UET</div>
            </div>
          </div>
        </b-scroll>
      </div>
    </div>
  </div>

</template>

<script>
  import MobileHeader from 'components/m-header'
  import {userCenter} from 'api'
  import noDataTip from 'components/no-data-tip'
  import BScroll from 'vue-slim-better-scroll';

  export default {
    name: "my-gift",
    data() {
      return {
        currentShow: true,
        isNull: true,
        isCashArr: [],
        timeList: [],
        isNullNext: true,
        noCacheArr: [],
        initPage:0,
        initPageNext:0,
        pullDownCfg:{
          threshold:45,
          stop:20
        }
      }
    },
    created() {
      this.getInfo()
    },
    methods: {
      getInfo() {
        const requestData = {
          "limit": 10,
          "offset": this.initPage,
          "couponStatus": 3,
          "couponType": 100
        }
        userCenter.myGift(requestData).then(res => {
          if (res.code == 10000) {
            if (res.pageInfo.total == 0) {
              this.isNull = true
            } else {
              this.isNull = false
              this.isCashArr = res.data
              console.log(res, '说的话')
              for (let i = 0; i < this.isCashArr.length; i++) {
                this.timeList.push({TimeList: this.formatMsgTime(this.isCashArr[i].couponEndtime)})
              }
            }
          } else {
            toast(res.message)
          }
        })
        const requestDatas = {
          "limit": 10,
          "offset": this.initPageNext,
          "couponStatus": 2,
          "couponType": 100
        }
        userCenter.myGift(requestDatas).then(res => {
          if (res.code == 10000) {
            if (res.pageInfo.total == 0) {
              this.isNullNext = true
            } else {
              this.isNullNext = false
              this.noCacheArr = res.data
              console.log(res, '说的话')
              for (let i = 0; i < this.noCacheArr.length; i++) {
                this.timeList.push({TimeList: this.formatMsgTime(this.isCashArr[i].couponEndtime)})
              }
            }
          } else {
            toast(res.message)
          }
        })
      },
      changeTab(num) {
        if (num == 1) {
          this.currentShow = true
        } else {
          this.currentShow = false
        }
      },
      formatMsgTime(timespan) {
        var dateTime = new Date(timespan);
        var year = dateTime.getFullYear() + 1 >= 10 ? dateTime.getFullYear() + 1 : '0' + dateTime.getFullYear();
        var month = dateTime.getMonth() + 1 >= 10 ? dateTime.getMonth() + 1 : '0' + dateTime.getMonth();
        var day = dateTime.getDate() >= 10 ? dateTime.getDate() : '0' + dateTime.getDate();
        var timeSpanStr;
        timeSpanStr = year + '-' + month + '-' + day + ' '
        return timeSpanStr;
      },
      loadMore(){
         this.initPage += 1
         this.getInfo()
      },
      loadRefresh(){

      }
    },
    components: {
      MobileHeader,
      noDataTip,
      BScroll
    }
  }
</script>

<style lang="scss" scoped>
  @import "~assets/scss/mobile";
  .Mygift_container {
    height: -webkit-fill-available;
    background-color: #f5f5f5;
    display: flex;
    flex-direction: column;
    .gift_content {
        display: flex;
        flex-direction: column;
        flex: 1;
      .gift_tab {
        text-align: center;
        margin: 0 auto;
        display: flex;
        flex-direction: row;
        width: 80%;
        padding-top: r(28);
        height: r(50);
        .is_cash {
          width: 50%;
          height: r(35);
          font-size: r(15);
          color: #333333;
          background-color: #fff;
          line-height: r(35);
          border-radius: r(4) r(0) r(0) r(4);
          &.active {
            background-color: #86A5F8;
            color: #fff;
          }
        }
        .no_cash {
          width: 50%;
          height: r(35);
          font-size: r(15);
          color: #333333;
          line-height: r(35);
          background-color: #fff;
          border-radius: r(0) r(4) r(4) r(0);
          &.active {
            background-color: #86A5F8;
            color: #fff;
          }
        }
      }
      .isCash_content {
        width: 100%;
        height: 100%;
        flex: 1;
        .discount_ticket {
          width: 85%;
          height: r(108);
          margin: r(20) auto;
          background-color: #fff;
          display: flex;
          flex-direction: row;
          padding: r(10) r(8);
          border-radius: r(5);
          .left_side {
            flex: 1;
            word-break: break-word;
            font-size: r(14);
            color: #787876;
            position: relative;
            .time_date {
              padding: r(8) r(0);
            }
            .id_num {
              display: flex;
              .id {
                width: r(40);
              }
            }
            .middle_line {
              position: absolute;
              top: - r(10);
              right: 0;
              width: r(15);
              height: r(108);
              background: url('~images/discount_white.png') no-repeat;
              background-size: 100%;
            }

          }
          .right_side {
            width: r(112);
            text-align: center;
            .side_money {
              font-size: 18px;
              color: #FF8b8b;
              padding-top: r(12);
            }
            .side_num {
              font-size: 16px;
              color: #ff8b8b;
              padding-top: r(10);
            }
          }
        }
      }
      .noCash_content {
        .discount_ticket {
          width: 85%;
          height: r(108);
          margin: r(20) auto;
          background-color: #FF8B8B;
          display: flex;
          flex-direction: row;
          padding: r(10) r(8);
          border-radius: r(5);
          .left_side {
            flex: 1;
            word-break: break-word;
            font-size: r(14);
            color: #fff;
            position: relative;
            .time_date {
              padding: r(8) r(0);
            }
            .id_num {
              display: flex;
              .id {
                width: r(40);
              }
            }

            .middle_line_next {
              position: absolute;
              top: - r(10);
              right: 0;
              width: r(15);
              height: r(108);
              background: url('~images/discount_pink.png') no-repeat;
              background-size: 100%;
            }
          }
          .right_side {
            width: r(112);
            text-align: center;
            .side_money {
              font-size: 18px;
              color: #fff;
              padding-top: r(12);
            }
            .side_num {
              font-size: 16px;
              color: #fff;
              padding-top: r(10);
            }
          }
        }
      }
    }
  }
</style>`

**Comment by yehoan** [comment]
我把文件发给你...

**Comment by yehoan** [comment]
我这个和之前的没区别

**Comment by yehoan** [comment]
改成v-show 也一样..

**Comment by yehoan** [comment]
<div class="Mygift_container">
    <MobileHeader>我的获赠</MobileHeader>
    <div class="gift_content">
      <div class="gift_tab">
        <div class="is_cash" :class="{'active':currentShow}" @click="changeTab(1)">已兑现</div>
        <div class="no_cash" :class="{'active':!currentShow}" @click="changeTab(2)">未兑现</div>
      </div>
      

      <div class="isCash_content" v-if="currentShow">
        <noDataTip v-if="isNull"></noDataTip>
        <BScroll
          ref="scroll"
          @pullingDown="loadRefresh"
          @pullingUp="loadMore"
          :refreshData= "[currentShow]"
          v-else
        >
          <div class="discount_ticket"  v-for="(list,num) in isCashArr">
            <div class="left_side">
              <p class="remark_info">{{list.remark}}</p>
              <p class="time_date">至{{timeList[num].TimeList}}过期</p>
              <div class="id_num" style="display: flex"><span style="float:left" class="id">单号:</span><span
                style="width: 70%">{{list.id}}</span></div>
              <div class="middle_line"></div>
            </div>
            <div class="right_side">
              <div class="side_money">¥ {{list.couponValueStr*0.01}}</div>
              <div class="side_num"> ={{list.couponValueStr}}UET</div>
            </div>
          </div>
        </BScroll>
      </div>
      
      <div class="noCash_content" v-else>
        <noDataTip v-if="isNullNext"></noDataTip>
        <b-scroll
          v-else
        >
          <div class="discount_ticket"  v-for="(list,num) in noCacheArr">
            <div class="left_side">
              <p class="remark_info">{{list.remark}}</p>
              <p class="time_date">至{{timeList[num].TimeList}}过期</p>
              <div class="id_num" style="display: flex"><span style="float:left" class="id">单号:</span><span
                style="width: 70%">{{list.id}}</span></div>
              <div class="middle_line_next"></div>
            </div>
            <div class="right_side">
              <div class="side_money">¥ {{list.couponValueStr*0.01}}</div>
              <div class="side_num"> ={{list.couponValueStr}}UET</div>
            </div>
          </div>
        </b-scroll>
      </div>
    </div>
  </div>

**Comment by yehoan** [comment]
`import MobileHeader from 'components/m-header'
  import {userCenter} from 'api'
  import noDataTip from 'components/no-data-tip'
  import BScroll from 'vue-slim-better-scroll';

  export default {
    name: "my-gift",
    data() {
      return {
        currentShow: true,
        isNull: true,
        isCashArr: [],
        timeList: [],
        isNullNext: true,
        noCacheArr: [],
        initPage:0,
        initPageNext:0,
        pullDownCfg:{
          threshold:45,
          stop:20
        }
      }
    },
    created() {
      this.getInfo()
    },
    methods: {
      getInfo() {
        const requestData = {
          "limit": 10,
          "offset": this.initPage,
          "couponStatus": 3,
          "couponType": 100
        }
        userCenter.myGift(requestData).then(res => {
          if (res.code == 10000) {
            if (res.pageInfo.total == 0) {
              this.isNull = true
            } else {
              this.isNull = false
              this.isCashArr = res.data
              console.log(res, '说的话')
              for (let i = 0; i < this.isCashArr.length; i++) {
                this.timeList.push({TimeList: this.formatMsgTime(this.isCashArr[i].couponEndtime)})
              }
            }
          } else {
            toast(res.message)
          }
        })
        const requestDatas = {
          "limit": 10,
          "offset": this.initPageNext,
          "couponStatus": 2,
          "couponType": 100
        }
        userCenter.myGift(requestDatas).then(res => {
          if (res.code == 10000) {
            if (res.pageInfo.total == 0) {
              this.isNullNext = true
            } else {
              this.isNullNext = false
              this.noCacheArr = res.data
              console.log(res, '说的话')
              for (let i = 0; i < this.noCacheArr.length; i++) {
                this.timeList.push({TimeList: this.formatMsgTime(this.isCashArr[i].couponEndtime)})
              }
            }
          } else {
            toast(res.message)
          }
        })
      },
      changeTab(num) {
        if (num == 1) {
          this.currentShow = true
        } else {
          this.currentShow = false
        }
      },
      formatMsgTime(timespan) {
        var dateTime = new Date(timespan);
        var year = dateTime.getFullYear() + 1 >= 10 ? dateTime.getFullYear() + 1 : '0' + dateTime.getFullYear();
        var month = dateTime.getMonth() + 1 >= 10 ? dateTime.getMonth() + 1 : '0' + dateTime.getMonth();
        var day = dateTime.getDate() >= 10 ? dateTime.getDate() : '0' + dateTime.getDate();
        var timeSpanStr;
        timeSpanStr = year + '-' + month + '-' + day + ' '
        return timeSpanStr;
      },
      loadMore(){
         this.initPage += 1
         this.getInfo()
      },
      loadRefresh(){

      }
    },
    components: {
      MobileHeader,
      noDataTip,
      BScroll
    }
  }`

**Comment by wannaxiao** [comment]
不是这样提供的😐，你还是自己排查吧，不要偷懒

**Comment by yehoan** [comment]
`@import "~assets/scss/mobile";
  .Mygift_container {
    height: -webkit-fill-available;
    background-color: #f5f5f5;
    display: flex;
    flex-direction: column;
    .gift_content {
        display: flex;
        flex-direction: column;
        flex: 1;
      .gift_tab {
        text-align: center;
        margin: 0 auto;
        display: flex;
        flex-direction: row;
        width: 80%;
        padding-top: r(28);
        height: r(50);
        .is_cash {
          width: 50%;
          height: r(35);
          font-size: r(15);
          color: #333333;
          background-color: #fff;
          line-height: r(35);
          border-radius: r(4) r(0) r(0) r(4);
          &.active {
            background-color: #86A5F8;
            color: #fff;
          }
        }
        .no_cash {
          width: 50%;
          height: r(35);
          font-size: r(15);
          color: #333333;
          line-height: r(35);
          background-color: #fff;
          border-radius: r(0) r(4) r(4) r(0);
          &.active {
            background-color: #86A5F8;
            color: #fff;
          }
        }
      }
      .isCash_content {
        width: 100%;
        height: 100%;
        flex: 1;
        .discount_ticket {
          width: 85%;
          height: r(108);
          margin: r(20) auto;
          background-color: #fff;
          display: flex;
          flex-direction: row;
          padding: r(10) r(8);
          border-radius: r(5);
          .left_side {
            flex: 1;
            word-break: break-word;
            font-size: r(14);
            color: #787876;
            position: relative;
            .time_date {
              padding: r(8) r(0);
            }
            .id_num {
              display: flex;
              .id {
                width: r(40);
              }
            }
            .middle_line {
              position: absolute;
              top: - r(10);
              right: 0;
              width: r(15);
              height: r(108);
              background: url('~images/discount_white.png') no-repeat;
              background-size: 100%;
            }

          }
          .right_side {
            width: r(112);
            text-align: center;
            .side_money {
              font-size: 18px;
              color: #FF8b8b;
              padding-top: r(12);
            }
            .side_num {
              font-size: 16px;
              color: #ff8b8b;
              padding-top: r(10);
            }
          }
        }
      }
      .noCash_content {
        .discount_ticket {
          width: 85%;
          height: r(108);
          margin: r(20) auto;
          background-color: #FF8B8B;
          display: flex;
          flex-direction: row;
          padding: r(10) r(8);
          border-radius: r(5);
          .left_side {
            flex: 1;
            word-break: break-word;
            font-size: r(14);
            color: #fff;
            position: relative;
            .time_date {
              padding: r(8) r(0);
            }
            .id_num {
              display: flex;
              .id {
                width: r(40);
              }
            }

            .middle_line_next {
              position: absolute;
              top: - r(10);
              right: 0;
              width: r(15);
              height: r(108);
              background: url('~images/discount_pink.png') no-repeat;
              background-size: 100%;
            }
          }
          .right_side {
            width: r(112);
            text-align: center;
            .side_money {
              font-size: 18px;
              color: #fff;
              padding-top: r(12);
            }
            .side_num {
              font-size: 16px;
              color: #fff;
              padding-top: r(10);
            }
          }
        }
      }
    }
  }`

**Comment by yehoan** [comment]
我这和聊天室一样的
啊

**Comment by yehoan** [comment]
不知道是什么原因

**Comment by yehoan** [comment]
之前的都是这样

**Comment by yehoan** [comment]
我都排查了N次了
代码都一样的
