### ISSUE TITLE
[Feature Request] pullUpConfig 能否提供支持 图片

### ISSUE THREAD

**Issue by linhuagen** [wannaxiao/vue-slim-better-scroll#7]
![image](https://user-images.githubusercontent.com/29427243/44324050-de7b5e00-a486-11e8-9e59-fde45d6fcd63.png)
 希望 能 支持 img ，能支持 HTML 标签内容,默认null; 如果同时设置了img, 则优先取img

**Comment by wannaxiao** [comment]
这里是有[slot](https://wannaxiao.github.io/vue-slim-better-scroll/docs/dist/#slots)的，但是粒度可能太大了，使用起来不友好。之后有时间看看会减小一下粒度( ꒪⌓꒪)

**Comment by linhuagen** [comment]
@wannaxiao 好的，总之谢谢你
